// Generated by Wrangler by running `wrangler types ./env.d.ts --env-interface CloudflareBindings`

interface CloudflareBindings {
  KV: KVNamespace
  NODE_ENV: string
  BETTER_AUTH_URL: string
  CLOUDFLARE_ACCOUNT_ID: string
  CLOUDFLARE_DATABASE_ID: string
  CLOUDFLARE_D1_TOKEN: string
  CLOUDFLARE_DATABASE_ID_PREVIEW: string
  RESEND_API_KEY: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  JWT_PRIVATE_KEY: string
  JWT_PUBLIC_KEY: string
  R2: R2Bucket
  DB: D1Database
}
